name: KS_Elixir
version: '${project.version}'
main: fr.kalium.elixir.KSElixir
api-version: '26.2'
description: Elixirs du serveur Event (8 potions allongees + un ingredient rare = une bouteille d'une heure).
authors: [KaLium]
softdepend: [KS_FioleExp]
