name: KS_LootBlocs
version: '${project.version}'
main: fr.kalium.lootblocs.KSLootBlocs
api-version: '26.2'
description: Loots des blocs du serveur Event (minerais, feuilles, verrue du Nether).
authors: [KaLium]
